# Generated by Django 3.2.16 on 2023-02-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.about')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.contact')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.personalinformation')),
                ('projects', models.ManyToManyField(to='feeds.Projects')),
                ('skills', models.ManyToManyField(to='feeds.Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
