# Generated by Django 3.2.16 on 2023-02-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_alter_userprofile_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feeds.about'),
        ),
    ]
